apiVersion: v1
kind: Service
metadata:
  name: interactive-lab
  labels: { app.kubernetes.io/name: interactive-lab }
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: interactive-lab }
  ports:
    - { name: http, port: 80, targetPort: http }
